/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tutorial

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {

    @Test
    fun appHasAGreeting() {
        println("Ini Test")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")

        // assertEquals(classUnderTest.greeting, "Hello World!!") // Error: org.opentest4j.AssertionFailedError: expected: <Hello World!> but was: <Hello World!!>

        assertEquals(classUnderTest.greeting, "Hello World!")
    }

}
